/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FifthStep: typeof import('./src/components/FifthStep.vue')['default']
    FirstStep: typeof import('./src/components/FirstStep.vue')['default']
    FourthStep: typeof import('./src/components/FourthStep.vue')['default']
    FouthStep: typeof import('./src/components/FouthStep.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondStep: typeof import('./src/components/SecondStep.vue')['default']
    ThirdStep: typeof import('./src/components/ThirdStep.vue')['default']
  }
}
